#!/usr/bin/python3
import sys, socket
import traceback

if __name__ == '__main__':
    bind_inft_name = str(sys.argv[1])
    to_ip, to_port = sys.argv[2].split(':')
    try: 
        udp = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        if(to_ip.endswith('255')): 
            udp.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
        udp.setsockopt(socket.SOL_SOCKET, 25, bind_inft_name.encode())
        sent_data = None
        while sent_data != 'EXIT': 
            sent_data = input()
            udp.sendto(sent_data.encode(), (to_ip, int(to_port)))
            print(f"{sent_data} DATA BROADCASTED")
    except socket.error as e:
        print(f"ERROR OCCURRED: {str(e)}")
        traceback.print_exception(*sys.exc_info())
        exit(-1)
